name: .NET Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore workloads
      run: |
        dotnet nuget locals all --clear 
        dotnet workload install maui --source https://aka.ms/dotnet7/nuget/index.json --source https://api.nuget.org/v3/index.json
        dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://aka.ms/dotnet7/nuget/index.json --source https://api.nuget.org/v3/index.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: |
        cd RadialGauge
        dotnet build --no-restore -c Release

    - name: Create nuget package
      run: |
        cd RadialGauge
        dotnet pack --no-restore -c Release

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: RadialGauge.nupkg
        path: RadialGauge/bin/Release/RadialGauge.1.0.3.nupkg
      
